services:
    frontend-app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "3000:80"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge