services:
    backend-app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/var/www/backend
        ports:
            - "9000:9000"
        networks:
            - app-network

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: sdesk
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/backend
        ports:
            - "8000:80"
        networks:
            - app-network

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: unless-stopped
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
